### ISSUE TITLE
Stopped working after latest HA update

### ISSUE THREAD

**Issue by rockchevy85** [philipp-luettecke/hassio-addons#3]
Pilight add-on fails to start after the latest HA update. Unfortunately after trying different rollbacks and restored backups, the only thing I am unable to rollback is the Supervisor version (which is now 2024.05.1) and the Pilight log shows the following error :

(/home/pilight/source/daemon-dev/libs/pilight/core/log.c #176) [May 14 16:54:38:602437] ERROR: The Broadcom 2836 failed to write to /sys/class/gpio/export for gpio exporting (Invalid argument)
pilight-daemon: /home/pilight/source/daemon-dev/libs/libuv/unix/poll.c:119: uv_poll_start: Assertion `!(((handle)->flags & (UV_CLOSING | UV_CLOSED)) != 0)' failed.
./run.sh: line 25:   228 Aborted                 (core dumped) /usr/local/sbin/pilight-daemon -F
[cmd] ./run.sh exited 134
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

**Comment by schluden** [comment]
same here. sidenote: the HACS GPIO Integration "ha-rpi_gpio" stopped working also. See here: https://github.com/thecode/ha-rpi_gpio/issues/255
⬇️⬇️
**I installed the updated version on another repository instead: https://github.com/jdeneef/ha_gpiod - which worked.**
⬆️⬆️
There is a second alternative which I didn't try: https://codeberg.org/raboof/ha-gpio

But they all have in common, they address the dependency used by this integration RPi.GPIO, which is not maintained for a long time, it is broken on new kernels! See here: https://sourceforge.net/p/raspberry-gpio-python/tickets/210/#4ed1

Maybe this information can help to repair the pilight add-on.

At least here is my error message of pilight, which differs vom OP:
`(/home/pilight/source/daemon-dev/libs/pilight/core/log.c #176) [May 22 14:27:11:695201] ERROR: The Broadcom 2711 failed to write to /sys/class/gpio/export for gpio exporting (Invalid argument)`
`(/home/pilight/source/daemon-dev/libs/pilight/core/log.c #176) [May 22 14:27:11:819433] ERROR: The Broadcom 2711 failed to write to /sys/class/gpio/export for gpio exporting (Invalid argument)`

**Comment by rockchevy85** [comment]
Sorry for the simple question, but are you saying if I install the updated ha-rpi_gpio from https://github.com/jdeneef/ha_gpiod then the standard pilight addon will start working again? Sorry, I just don't want to break it as it is currently working but on the old software version.

**Comment by Hellcube** [comment]
same deal...any way to fix it?
(/home/pilight/source/daemon-dev/libs/pilight/core/log.c #176) [Sep 23 18:36:03:815924] ERROR: The Broadcom 2711 failed to write to /sys/class/gpio/export for gpio exporting (Invalid argument)
pilight-daemon: /home/pilight/source/daemon-dev/libs/libuv/unix/poll.c:119: uv_poll_start: Assertion `!(((handle)->flags & (UV_CLOSING | UV_CLOSED)) != 0)' failed.
./run.sh: line 25:   227 Aborted                 (core dumped) /usr/local/sbin/pilight-daemon -F -D
[cmd] ./run.sh exited 134
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by rockchevy85** [comment]
I gave up on this in the end. Installed pilight on a separate Pi and do all the service calls over TCP, been running fine for about 3 months with the HA updated to latest release - just not using the pilight add-on anymore.

**Comment by Hellcube** [comment]
So there is no way i can fix it. I like to have it all on one machine. Do you have any idea what could be wrong?

**Comment by rockchevy85** [comment]
Sorry I don't know, that's why I asked on here.

**Comment by schluden** [comment]
The Home Assistant Core Version is not the problem. Its the Home Assistant OS Version!
Go Back to Version 12.2, and it will work again. There were kernel changes made, so that the GPIO functions differently (I guess).

1. !!Create full backup!!
2. Download Terminal Add-On
3. Type: ha os update --version 12.2

Done!


> Am 24.09.2024 um 14:11 schrieb Hellcube ***@***.***>:
> 
> Do

**Comment by philipp-luettecke** [comment]
Hello everyone,
I've been inactive for quite some time - sorry about that.

For now I did not have the chance to dig deeper into the issue, so I just tried rebuilding the images with the newest release of pilight-stable.

So maybe someone could try the latest image versions once more?
https://hub.docker.com/layers/philippluettecke/hassio-pilight-armv7/1.8.0/images/sha256-a6acef418fb34d5f6de8a18fe984f0b593f2ddeade44d07275f91786288a73d5?context=repo

Best regards!

**Comment by Hellcube** [comment]
(/home/pilight/source/daemon-dev/libs/pilight/core/log.c #176) [Sep 24 17:51:19:122460] ERROR: The Broadcom 2711 failed to write to /sys/class/gpio/export for gpio exporting (Invalid argument)
pilight-daemon: /home/pilight/source/daemon-dev/libs/libuv/unix/poll.c:119: uv_poll_start: Assertion `!(((handle)->flags & (UV_CLOSING | UV_CLOSED)) != 0)' failed.
./run.sh: line 25:   227 Aborted                 (core dumped) /usr/local/sbin/pilight-daemon -F -D
[cmd] ./run.sh exited 134
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by philipp-luettecke** [comment]
Unfortunate..
Based on the following Reddit Thread I tried building the library, pilight uses for GPIO communication, from scratch including pilight on-top. 
https://www.reddit.com/r/homebridge/comments/18cn2lk/cant_install_pilight_on_any_recent_homebridge/

And for me compilation worked fine.

But I just recognized, that I'm using an older base image.

Maybe someone could check again with Version 1.8.1?

**Comment by philipp-luettecke** [comment]
But I also just found https://github.com/wiringX/wiringX/issues/126
This seems to be the main issue here and is not yet fixed.

After  someone fixing wiringX library, I can recompile this Addon.

**Comment by Hellcube** [comment]
same log:
[cmd] ./run.sh exited 134
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by schluden** [comment]
Revert to Version 12.2, and it will work. I am fine with it. 

> Am 24.09.2024 um 21:11 schrieb ***@***.***:
> 
> to Version 12.2, and it will work

**Comment by ReWo77** [comment]
I get the same error like Hellcube with 1.8.1. If I restore 1.7.2 everything is working again...

Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1
